---
- name: Deploy coffee-project
  hosts: "{{ run_on_host }}"
  become: yes
  become_method: sudo
  vars:
    docker_user: "{{ docker_user }}"
    docker_password: "{{ docker_password }}"
    image_version: "{{ image_version }}"
  tasks:
    - name: Login to docker
      shell: "echo {{ docker_password }} | docker login ghcr.io -u {{ docker_user }} --password-stdin"

    - name: Pull Docker image
      shell: "docker pull ghcr.io/subodh30/coffee-project:{{ image_version }}"

    - name: Stop container if running
      shell: "docker stop coffee-app || true"
      ignore_errors: yes

    - name: Remove container if exists
      shell: "docker rm coffee-app || true"
      ignore_errors: yes

    - name: Run application
      shell: "docker run -d -p 3000:3000 --name coffee-app ghcr.io/subodh30/coffee-project:{{ image_version }}"

    - name: Wait till the App is up
      uri:
        url: "http://127.0.0.1:3000/"
        return_content: yes
        validate_certs: no
        status_code:
          - 200
      register: website_health_check
      until: website_health_check.status == 200
      retries: 20
      delay: 10

    - name: Remove old docker images
      shell: "docker image prune -f"
      ignore_errors: yes
